GENDER_CHOICES = (
    ('Female', 'Female'),
    ('Male', 'Male'),
    ('Other', 'Other'),
)
CITIZENSHIP_CHOICE = (('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'),
                      ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AG', 'Antigua and Barbuda'),
                      ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'),
                      ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'),
                      ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'),
                      ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'),
                      ('BO', 'Bolivia (Plurinational State of)'), ('BA', 'Bosnia and Herzegovina'),
                      ('BW', 'Botswana'), ('BR', 'Brazil'), ('IO', 'British Indian Ocean Territory'),
                      ('VI', 'Virgin Islands (U.S.)'), ('BN', 'Brunei Darussalam'), ('BG', 'Bulgaria'),
                      ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KH', 'Cambodia'), ('CM', 'Cameroon'),
                      ('CA', 'Canada'), ('CV', 'Cabo Verde'), ('KY', 'Cayman Islands'), ('CF', 'Central African Republic'),
                      ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('KM', 'Comoros'),
                      ('CG', 'Congo'), ('CD', 'Congo (Democratic Republic of the)'), ('CK', 'Cook Islands'),
                      ('CR', 'Costa Rica'), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'),
                      ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'),
                      ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'),
                      ('EE', 'Estonia'), ('ET', 'Ethiopia'), ('FK', 'Falkland Islands (Malvinas)'), ('FO', 'Faroe Islands'),
                      ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'),
                      ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'),
                      ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'),
                      ('GT', 'Guatemala'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'),
                      ('VA', 'Holy See'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'),
                      ('IN', 'India'), ('ID', 'Indonesia'), ('CI', "Côte d'Ivoire"), ('IR', 'Iran (Islamic Republic of)'),
                      ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'),
                      ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KW', 'Kuwait'),
                      ('KG', 'Kyrgyzstan'), ('LA', "Lao People's Democratic Republic"), ('LV', 'Latvia'), ('LB', 'Lebanon'),
                      ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'),
                      ('LU', 'Luxembourg'), ('MO', 'Macao'), ('MK', 'Macedonia (the former Yugoslav Republic of)'),
                      ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'),
                      ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'),
                      ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia (Federated States of)'),
                      ('MD', 'Moldova (Republic of)'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('MS', 'Montserrat'),
                      ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'),
                      ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'),
                      ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk Island'),
                      ('KP', "Korea (Democratic People's Republic of)"), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'),
                      ('PW', 'Palau'), ('PS', 'Palestine, State of'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'),
                      ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('PL', 'Poland'),
                      ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RO', 'Romania'), ('RU', 'Russian Federation'),
                      ('RW', 'Rwanda'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('KN', 'Saint Kitts and Nevis'),
                      ('LC', 'Saint Lucia'), ('MF', 'Saint Martin (French part)'), ('PM', 'Saint Pierre and Miquelon'),
                      ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'),
                      ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'),
                      ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SK', 'Slovakia'), ('SI', 'Slovenia'),
                      ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('KR', 'Korea (Republic of)'),
                      ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SZ', 'Swaziland'),
                      ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syrian Arab Republic'), ('TJ', 'Tajikistan'),
                      ('TZ', 'Tanzania, United Republic of'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'),
                      ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Turkey'),
                      ('TM', 'Turkmenistan'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'),
                      ('GB', 'United Kingdom of Great Britain and Northern Ireland'), ('US', 'United States of America'),
                      ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela (Bolivarian Republic of)'),
                      ('VN', 'Viet Nam'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'))
DESTINATION_CHOICE = CITIZENSHIP_CHOICE

EVENT_TYPE_CHOICE = (('Course', 'Course'), ('Consultation', 'Consultation'), ('Lecture', 'Lecture'), ('Show', 'Show'), ('Talk', 'Talk'), ('Workshop', 'Workshop'), ('Others', 'Others'))
EVENT_FREQ_CHOICE = (('Once', 'Once'), ('Multiple', 'Multiple'),('Fexible', 'Fexible'))
EVENT_DURATION_CHOICE = (('Less than 2 hours', 'Less than 2 hours'), ('2 to 4 hours', '2 to 4 hours'), ('4 to 8 hours', '4 to 8 hours'), ('More than 8 hours', 'More than 8 hours'))

ORG_TYPE_CHOICE = (('Association', 'Association'), ('Center', 'Center'), ('Club', 'Club'), ('Community', 'Community'), ('Company', 'Company'),
                   ('Cooperative/Collective', 'Cooperative/Collective'), ('Government/Town Council/Village', 'Government/Town Council/Village'), ('Institute', 'Institute'),
                   ('Museum', 'Museum'), ('NGO/Foundation', 'NGO/Foundation'), ('Park', 'Park'), ('Political Party', 'Political Party'),
                   ('School/Nursery/Kindergarten', 'School/Nursery/Kindergarten'), ('Social Enterprise', 'Social Enterprise'), ('Society', 'Society'),
                   ('Station & Network', 'Station & Network'), ('Support Group', 'Support Group'), ('Union', 'Union'), ('University', 'University'), ('Others', 'Others'))

EXPERTISE_CHOICE = ((1, 'Accounting & Auditing'), (2, 'Admin & Clerical'), (3, 'Agriculture'), (4, 'Automotive'),
                    (5, 'Banking'), (6, 'Biotech'), (7, 'Broadcast'), (8, 'Business Development'), (9, 'Construction'),
                    (10, 'Consultant'), (11, 'Customer Service'), (12, 'Design'), (13, 'Distribution'),
                    (14, 'Education'), (15, 'Engineering'), (16, 'Entry Level'), (17, 'Executive'),
                    (18, 'Facilities'), (19, 'Finance'), (20, 'Franchise'), (21, 'General Business'),
                    (22, 'General Labor'), (23, 'Government'), (24, 'Grocery'), (25, 'Health Care'),
                    (26, 'Hospitality'), (27, 'Hotel'), (28, 'Human Resources'), (29, 'Information Technology'),
                    (30, 'Installation'), (31, 'Insurance'), (32, 'Inventory'), (33, 'Journalism'),
                    (34, 'Journalism'), (35, 'Legal'), (36, 'Legal Admin'), (37, 'Maint'), (38, 'Management'),
                    (39, 'Manufacturing'), (40, 'Marketing'), (41, 'Media'), (42, 'New Grad'), (43, 'Newspaper'),
                    (44, 'Nonprofit'), (45, 'Nurse'), (46, 'Other'), (47, 'Pharmaceutical'), (48, 'Planning'),
                    (49, 'Procurement'), (50, 'Professional Services'), (51, 'Purchasing'), (52, 'QA'),
                    (53, 'Quality Control'), (54, 'Real Estate'), (55, 'Repair'), (56, 'Research'),
                    (57, 'Restaurant/Food Service'), (58, 'Retail'), (59, 'Sales'), (60, 'Science'),
                    (61, 'Shipping'), (62, 'Skilled Labor'), (63, 'Social Services'), (64, 'Strategy'),
                    (65, 'Supply Chain'), (66, 'Teaching'), (67, 'Telecommunications'), (68, 'Trades'),
                    (69, 'Training'), (70, 'Transportation'), (71, 'Warehouse'))

# 71 expertise
EXPERTISE_LIST = ['Accounting & Auditing', 'Admin & Clerical', 'Agriculture', 'Automotive', 'Banking', 'Biotech', 'Broadcast',
                  'Business Development', 'Construction', 'Consultant', 'Customer Service', 'Design', 'Distribution',
                  'Education', 'Engineering', 'Entry Level', 'Executive', 'Facilities', 'Finance', 'Franchise',
                  'General Business', 'General Labor', 'Government', 'Grocery', 'Health Care', 'Hospitality',
                  'Hotel', 'Human Resources', 'Information Technology', 'Installation', 'Insurance', 'Inventory',
                  'Journalism', 'Journalism', 'Legal', 'Legal Admin', 'Maint', 'Management', 'Manufacturing',
                  'Marketing', 'Media', 'New Grad', 'Newspaper', 'Nonprofit', 'Nurse', 'Other', 'Pharmaceutical',
                  'Planning', 'Procurement', 'Professional Services', 'Purchasing', 'QA', 'Quality Control',
                  'Real Estate', 'Repair', 'Research', 'Restaurant/Food Service', 'Retail', 'Sales', 'Science',
                  'Shipping', 'Skilled Labor', 'Social Services', 'Strategy', 'Supply Chain', 'Teaching',
                  'Telecommunications', 'Trades', 'Training', 'Transportation', 'Warehouse']

LANGUAGE_CHOICE = (('ab', 'Abkhazian'), ('aa', 'Afar'), ('af', 'Afrikaans'), ('ak', 'Akan'), ('sq', 'Albanian'), ('am', 'Amharic'), ('ar', 'Arabic'), ('an', 'Aragonese'), ('hy', 'Armenian'), ('as', 'Assamese'), ('av', 'Avaric'), ('ae', 'Avestan'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('bm', 'Bambara'), ('ba', 'Bashkir'), ('eu', 'Basque'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('bh', 'Bihari languages'), ('bi', 'Bislama'), ('bs', 'Bosnian'), ('br', 'Breton'), ('bg', 'Bulgarian'), ('my', 'Burmese'), ('ca', 'Catalan, Valencian'), ('ch', 'Chamorro'), ('ce', 'Chechen'), ('ny', 'Chichewa, Chewa, Nyanja'), ('zh', 'Chinese'), ('cv', 'Chuvash'), ('kw', 'Cornish'), ('co', 'Corsican'), ('cr', 'Cree'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('dv', 'Divehi, Dhivehi, Maldivian'), ('nl', 'Dutch, Flemish'), ('dz', 'Dzongkha'), ('en', 'English'), ('eo', 'Esperanto'), ('et', 'Estonian'), ('ee', 'Ewe'), ('fo', 'Faroese'), ('fj', 'Fijian'), ('fi', 'Finnish'), ('fr', 'French'), ('ff', 'Fulah'), ('gl', 'Galician'), ('ka', 'Georgian'), ('de', 'German'), ('el', 'Greek'), ('gn', 'Guarani'), ('gu', 'Gujarati'), ('ht', 'Haitian Creole'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('hz', 'Herero'), ('hi', 'Hindi'), ('ho', 'Hiri Motu'), ('hu', 'Hungarian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ie', 'Interlingue, Occidental'), ('ga', 'Irish'), ('ig', 'Igbo'), ('ik', 'Inupiaq'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('iu', 'Inuktitut'), ('ja', 'Japanese'), ('jv', 'Javanese'), ('kl', 'Kalaallisut, Greenlandic'), ('kn', 'Kannada'), ('kr', 'Kanuri'), ('ks', 'Kashmiri'), ('kk', 'Kazakh'), ('km', 'Central Khmer'), ('ki', 'Kikuyu, Gikuyu'), ('rw', 'Kinyarwanda'), ('ky', 'Kirghiz, Kyrgyz'), ('kv', 'Komi'), ('kg', 'Kongo'), ('ko', 'Korean'), ('ku', 'Kurdish'), ('kj', 'Kuanyama, Kwanyama'), ('la', 'Latin'), ('lb', 'Luxembourgish, Letzeburgesch'), ('lg', 'Ganda'), ('li', 'Limburgan, Limburger, Limburgish'), ('ln', 'Lingala'), ('lo', 'Lao'), ('lt', 'Lithuanian'), ('lu', 'Luba'), ('lv', 'Latvian'), ('gv', 'Manx'), ('mk', 'Macedonian'), ('mg', 'Malagasy'), ('ms', 'Malay'), ('ml', 'Malayalam'), ('mt', 'Maltese'), ('mi', 'Maori'), ('mr', 'Marathi'), ('mh', 'Marshallese'), ('mn', 'Mongolian'), ('na', 'Nauru'), ('nv', 'Navajo, Navaho'), ('nd', 'North Ndebele'), ('ne', 'Nepali'), ('ng', 'Ndonga'), ('nb', 'Norwegian Bokmål'), ('nn', 'Norwegian Nynorsk'), ('no', 'Norwegian'), ('ii', 'Sichuan Yi, Nuosu'), ('nr', 'South Ndebele'), ('oc', 'Occitan'), ('oj', 'Ojibwa'), ('cu', 'Slavic'), ('om', 'Oromo'), ('or', 'Oriya'), ('os', 'Ossetian, Ossetic'), ('pa', 'Panjabi, Punjabi'), ('pi', 'Pali'), ('fa', 'Persian'), ('pl', 'Polish'), ('ps', 'Pashto, Pushto'), ('pt', 'Portuguese'), ('qu', 'Quechua'), ('rm', 'Romansh'), ('rn', 'Rundi'), ('ro', 'Romanian, Moldavian, Moldovan'), ('ru', 'Russian'), ('sa', 'Sanskrit'), ('sc', 'Sardinian'), ('sd', 'Sindhi'), ('se', 'Northern Sami'), ('sm', 'Samoan'), ('sg', 'Sango'), ('sr', 'Serbian'), ('gd', 'Gaelic, Scottish Gaelic'), ('sn', 'Shona'), ('si', 'Sinhala, Sinhalese'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('so', 'Somali'), ('st', 'Southern Sotho'), ('es', 'Spanish, Castilian'), ('su', 'Sundanese'), ('sw', 'Swahili'), ('ss', 'Swati'), ('sv', 'Swedish'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('ti', 'Tigrinya'), ('bo', 'Tibetan'), ('tk', 'Turkmen'), ('tl', 'Tagalog'), ('tn', 'Tswana'), ('to', 'Tonga'), ('tr', 'Turkish'), ('ts', 'Tsonga'), ('tt', 'Tatar'), ('tw', 'Twi'), ('ty', 'Tahitian'), ('ug', 'Uighur, Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('ve', 'Venda'), ('vi', 'Vietnamese'), ('vo', 'Volapük'), ('wa', 'Walloon'), ('cy', 'Welsh'), ('wo', 'Wolof'), ('fy', 'Western Frisian'), ('xh', 'Xhosa'), ('yi', 'Yiddish'), ('yo', 'Yoruba'), ('za', 'Zhuang, Chuang'), ('zu', 'Zulu'))

#184 MAIN LANGUAGES
LANGUAGE_LIST = ['Abkhaz', 'Afar', 'African', 'Afrikaans', 'Akan', 'Albanian', 'Alemannic', 'Alsatian', 'Amerindian',
             'Amerindian dialects', 'Amharic', 'Angaur', 'Arabic', 'Aramaic', 'Armenian', 'Asian', 'Assamese',
             'Assyrian', 'Aymara', 'Azerbaijani', 'Azeri', 'Bahasa', 'Bahasa Indonesia', 'Balinese', 'Balochi',
             'Baluchi', 'Bambara', 'Bandjabi', 'Bangla', 'Bantu', 'Bapounou/Eschira', 'Barbuda', 'Bari', 'Basque',
             'Belorussian/White Russian', 'Bemba', 'Bengali', 'Berber', 'Bhojpuri', 'Bhotes', 'Bicol', 'Bislama',
             'Bojpoori', 'Bokmål Norwegian', 'Bosnian', 'Brahui', 'Brazilero', 'Breton', 'Bubi', 'Bulgarian', 'Burmese',
             'Burushaski', 'Cakchiquel', 'Cantonese', 'Carib', 'Carolinian', 'Castilian', 'Catalan', 'Catalán',
             'Cebuano', 'Chichewa', 'Chilomwe', 'Chinese/Mandarin', 'Chinyanja', 'Chisena', 'Chitonga', 'Chitumbuka',
             'Chiyao', 'Chukese', 'Circassian', 'Cisena', 'Corsican', 'Creole', 'Criolo', 'Criuolo', 'Croatian',
             'Cushitic', 'Czech', 'Dagomba', 'Danish', 'Dari', 'Dimli', 'Dinka', 'Dioula', 'Djerma', 'Dutch',
             'Dutch/Flemish', 'Dzongkha', 'Echuwabo', 'Elomwe', 'Emakhuwa', 'English', 'Estonian', 'Ewe', 'Ewé',
             'Fang', 'Faroese', 'Farsi', 'Fijian', 'Filipino', 'Finnish', 'Flemish', 'Fon', 'Foochow', 'French',
             'French patois', 'Frisian', 'Fula', 'Fulani', 'Fuzhou', 'Ga', 'Gaelic', 'Gagauz', 'Galician', 'Galole',
             'Gan', 'Ganda', 'Garifuna', 'Georgian', 'German', 'Greek', 'Greenlandic', 'Guaragigna', 'Guaraní', 'Gujarati',
             'Hainan', 'Haitian', 'Hakka', 'Hassaniya Arabic', 'Hausa', 'Hebrew', 'Herero', 'Hiligaynon', 'Hindi',
             'Hindi/Urdu', 'Hindko', 'Hindustani', 'Hiri Motu', 'Hokkien', 'Hokkien-Taiwanese', 'Hungarian',
             'I-Kiribati', 'Iban', 'Ibo', 'Icelandic', 'Ilocano', 'Ilonggo', 'Indian', 'Indonesia', 'Inuit',
             'Irish', 'IsiXhosa', 'IsiZulu', 'Italian', 'Jamaican', 'Japanese', 'Javanese', 'Jola', 'Kabardian',
             'Kabyé', 'Kadazan', 'Kalanga', 'Kannada', 'Kaonda', 'Kapingamarangi', 'Kashmiri', 'Kazak', 'Kekchi',
             'Kemak', 'Khmer', 'Kikongo', 'Kinyarwanda', 'Kiribati', 'Kirundi', 'Kiswahili', 'Korean', 'Kosrean',
             'Krio', 'Kunama', 'Kurdish', 'Kyrgyz', 'Lao', 'Latin', 'Latvian', 'Lingala', 'Lithuanian', 'Lozi', 'Luganda',
             'Lunda', 'Luri', 'Luvale', 'Luxermbourgish', 'Macedonian', 'Maithali', 'Malagasy', 'Malay', 'Malayalam',
             'Malayo-Polynesian', 'Maldivian Dhivehi', 'Malinké', 'Maltese', 'Mam', 'Mambae', 'Mandinka',
             'Maori', 'Marathi', 'Marshallese', 'Mayan', 'Melanesian', 'Melayu', 'Mende', 'Min', 'Mina', 'Minbei',
             'Minnan', 'Mirandese', 'Moldovan', 'Mon-Khmer', 'Mongolian', 'Monokutuba', 'Montenegrin',
             'Monégasque', 'Moroccan Arabic', 'Moshi-Dagomba', 'Mozambican', 'Myene', 'Nahua', 'Nahuatl', 'Nama',
             'Nauruan', 'Ndebele/Sindebele', 'Nepalese', 'Nepali', 'Niger-Congo', 'Nilo-Hamitic', 'Nilo-Saharan', 'Nilotic',
             'Nordic', 'Nubian', 'Nuer', 'Nui', 'Nukuoro', 'Nyanja', 'Nynorsk Norwegian', 'Nzebi', 'Oriya', 'Orominga',
             'Oshivambo', 'Palauan', 'Pampango', 'Pangasinense', 'Panjabi', 'Pashtu', 'Persian', 'Pohnpeian', 'Polish',
             'Portuguese', 'Portunol', 'Provençal', 'Pulaar', 'Punjabi', 'Quechua', 'Quiche', 'Quéchua', 'Roma', 'Romanian',
             'Romansch', 'Russian', 'Sami', 'Samoan', 'Sangho', 'Sanskrit', 'Sara', 'Scots Gaelic',
             'Sekgalagadi', 'Sepedi', 'Serbian', 'Serbo-Croatian', 'Seselwa Creole', 'Sesotho', 'Setswana', 'Shanghaiese',
             'Shikomoro', 'Shilluk', 'Shona', 'Siamese', 'Sindhi', 'Sinhala', 'Siraiki', 'Siswati', 'Slovak', 'Slovene',
             'Slovenian', 'Somali', 'Soninke', 'Sonsoralese', 'Spanish', 'Sudanic', 'Surinamese', 'Susu', 'Swahili',
             'Swahili/Arabic', 'Swedish', 'Ta Bedawie', 'Tagalog', 'Taiwanese', 'Tajik', 'Tamang', 'Tamil', 'Telugu',
             'Temne', 'Teochew', 'Tetum', 'Thai', 'Tharu', 'Tibetan', 'Tigre', 'Tigrigna', 'Tigrinya', 'Tobi', 'Tok Pisin',
             'Tonga', 'Tongan', 'Tosk', 'Tshiluba', 'Turkic', 'Turkish', 'Turkmen', 'Tuvaluan', 'Ukrainian', 'Ulithian',
             'Urdu', 'Uzbek', 'Vietnamese', 'Waray', 'Welsh', 'Woleaian', 'Wolof', 'Wu', 'Xhosa', 'Xiang', 'Xichangana',
             'Xinca', 'Xitsonga', 'Yapase', 'Yezidi', 'Yoruba', 'Yue', 'Zande', 'Zulu']

# 154 subjects
SUBJECT_LIST = ['Accounting', 'Analytics', 'Assessing Performance', 'Auditing', 'Balanced Scorecard', 'Behavioral Economics',
                'Boards', 'Branding', 'Budgeting', 'Business Education', 'Business History', 'Business Law', 'Business Models',
                'Business Processes', 'Business Writing', 'Career Planning', 'Change Management', 'Coaching', 'Collaboration',
                'Communication', 'Compensation', 'Competition', 'Competitive Strategy', 'Conflict', 'Corporate Communications',
                'Corporate Governance', 'Costs', 'Creativity', 'Crisis Communication', 'Crisis Management',
                'Cross-Cultural Management', 'Currency', 'Customer Service', 'Customers', 'Data', 'Decision Making',
                'Delegation', 'Demographics', 'Design', 'Developing Employees', 'Difficult Conversations',
                'Disruptive Innovation', 'Diversity', 'Downsizing', 'Economic Development', 'Economics', 'Economics & Society',
                'Economy', 'Education', 'Emerging Markets', 'Emotional Intelligence', 'Employee Retention',
                'Entrepreneurial Finance', 'Entrepreneurial Management', 'Entrepreneurship', 'Ethics',
                'Executive Compensation', 'Experimentation', 'Finance & Accounting', 'Financial Analysis',
                'Financial Management', 'Financial Markets', 'Firing', 'Forecasting', 'Founders', 'Gender',
                'Generational Issues', 'Giving Feedback', 'Global Strategy', 'Globalization', 'Government', 'Growth Strategy',
                'Health', 'Hiring', 'Human Resource Management', 'Influence', 'Informal Leadership', 'Innovation',
                'Intellectual Property', 'International Business', 'Internet', 'IPO', 'IT', 'Job Search', 'Joint Ventures',
                'Knowledge Management', 'Labor', 'Leadership', 'Leadership & Managing People', 'Leadership Development',
                'Leadership Transitions', 'Leading Teams', 'Managing Organizations', 'Managing People', 'Managing Uncertainty',
                'Managing Up', 'Managing Yourself', 'Manufacturing', 'Market Research', 'Marketing', 'Meetings',
                'Mergers & Acquisitions', 'Mobile', 'Motivating People', 'National Competitiveness', 'Negotiations',
                'Networking', 'Operations', 'Operations Management', 'Organizational Culture', 'Organizational Structure',
                'Performance Measurement', 'Personnel Policies', 'Policy', 'Presentations', 'Pricing', 'Product Development',
                'Productivity', 'Professional Transitions', 'Project Management', 'Psychology', 'Public Relations',
                'Public-Private Partnerships', 'Race', 'Receiving Feedback', 'Recession', 'Regulation', 'Reorganization',
                'Research & Development', 'Retirement', 'Risk Management', 'Sales', 'Sales & Marketing', 'Security & Privacy',
                'Sexual Orientation', 'Shared Value', 'Social Enterprise', 'Social Platforms', 'Social Responsibility',
                'Strategic Planning', 'Strategic Thinking', 'Strategy', 'Strategy Execution', 'Stress', 'Succession Planning',
                'Supply Chain', 'Sustainability', 'Talent Management', 'Technology', 'Time Management', 'Transparency',
                'Venture Capital', 'Work-Life Balance', 'Workspaces']

SUBJECT_CHOICE = ((1, 'Accounting'), (2, 'Analytics'), (3, 'Assessing Performance'), (4, 'Auditing'), (5, 'Balanced Scorecard'), (6, 'Behavioral Economics'), (7, 'Boards'), (8, 'Branding'), (9, 'Budgeting'), (10, 'Business Education'), (11, 'Business History'), (12, 'Business Law'), (13, 'Business Models'), (14, 'Business Processes'), (15, 'Business Writing'), (16, 'Career Planning'), (17, 'Change Management'), (18, 'Coaching'), (19, 'Collaboration'), (20, 'Communication'), (21, 'Compensation'), (22, 'Competition'), (23, 'Competitive Strategy'), (24, 'Conflict'), (25, 'Corporate Communications'), (26, 'Corporate Governance'), (27, 'Costs'), (28, 'Creativity'), (29, 'Crisis Communication'), (30, 'Crisis Management'), (31, 'Cross-Cultural Management'), (32, 'Currency'), (33, 'Customer Service'), (34, 'Customers'), (35, 'Data'), (36, 'Decision Making'), (37, 'Delegation'), (38, 'Demographics'), (39, 'Design'), (40, 'Developing Employees'), (41, 'Difficult Conversations'), (42, 'Disruptive Innovation'), (43, 'Diversity'), (44, 'Downsizing'), (45, 'Economic Development'), (46, 'Economics'), (47, 'Economics & Society'), (48, 'Economy'), (49, 'Education'), (50, 'Emerging Markets'), (51, 'Emotional Intelligence'), (52, 'Employee Retention'), (53, 'Entrepreneurial Finance'), (54, 'Entrepreneurial Management'), (55, 'Entrepreneurship'), (56, 'Ethics'), (57, 'Executive Compensation'), (58, 'Experimentation'), (59, 'Finance & Accounting'), (60, 'Financial Analysis'), (61, 'Financial Management'), (62, 'Financial Markets'), (63, 'Firing'), (64, 'Forecasting'), (65, 'Founders'), (66, 'Gender'), (67, 'Generational Issues'), (68, 'Giving Feedback'), (69, 'Global Strategy'), (70, 'Globalization'), (71, 'Government'), (72, 'Growth Strategy'), (73, 'Health'), (74, 'Hiring'), (75, 'Human Resource Management'), (76, 'Influence'), (77, 'Informal Leadership'), (78, 'Innovation'), (79, 'Intellectual Property'), (80, 'International Business'), (81, 'Internet'), (82, 'IPO'), (83, 'IT'), (84, 'Job Search'), (85, 'Joint Ventures'), (86, 'Knowledge Management'), (87, 'Labor'), (88, 'Leadership'), (89, 'Leadership & Managing People'), (90, 'Leadership Development'), (91, 'Leadership Transitions'), (92, 'Leading Teams'), (93, 'Managing Organizations'), (94, 'Managing People'), (95, 'Managing Uncertainty'), (96, 'Managing Up'), (97, 'Managing Yourself'), (98, 'Manufacturing'), (99, 'Market Research'), (100, 'Marketing'), (101, 'Meetings'), (102, 'Mergers & Acquisitions'), (103, 'Mobile'), (104, 'Motivating People'), (105, 'National Competitiveness'), (106, 'Negotiations'), (107, 'Networking'), (108, 'Operations'), (109, 'Operations Management'), (110, 'Organizational Culture'), (111, 'Organizational Structure'), (112, 'Performance Measurement'), (113, 'Personnel Policies'), (114, 'Policy'), (115, 'Presentations'), (116, 'Pricing'), (117, 'Product Development'), (118, 'Productivity'), (119, 'Professional Transitions'), (120, 'Project Management'), (121, 'Psychology'), (122, 'Public Relations'), (123, 'Public-Private Partnerships'), (124, 'Race'), (125, 'Receiving Feedback'), (126, 'Recession'), (127, 'Regulation'), (128, 'Reorganization'), (129, 'Research & Development'), (130, 'Retirement'), (131, 'Risk Management'), (132, 'Sales'), (133, 'Sales & Marketing'), (134, 'Security & Privacy'), (135, 'Sexual Orientation'), (136, 'Shared Value'), (137, 'Social Enterprise'), (138, 'Social Platforms'), (139, 'Social Responsibility'), (140, 'Strategic Planning'), (141, 'Strategic Thinking'), (142, 'Strategy'), (143, 'Strategy Execution'), (144, 'Stress'), (145, 'Succession Planning'), (146, 'Supply Chain'), (147, 'Sustainability'), (148, 'Talent Management'), (149, 'Technology'), (150, 'Time Management'), (151, 'Transparency'), (152, 'Venture Capital'), (153, 'Work-Life Balance'), (154, 'Workspaces'))
