GENDER_CHOICES = (
    ('F', 'Female'),
    ('M', 'Male'),
    ('O', 'Other'),
)
CITIZENSHIP_CHOICE = (('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'),
                      ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AG', 'Antigua and Barbuda'),
                      ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'),
                      ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'),
                      ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'),
                      ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'),
                      ('BO', 'Bolivia (Plurinational State of)'), ('BA', 'Bosnia and Herzegovina'),
                      ('BW', 'Botswana'), ('BR', 'Brazil'), ('IO', 'British Indian Ocean Territory'),
                      ('VI', 'Virgin Islands (U.S.)'), ('BN', 'Brunei Darussalam'), ('BG', 'Bulgaria'),
                      ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KH', 'Cambodia'), ('CM', 'Cameroon'),
                      ('CA', 'Canada'), ('CV', 'Cabo Verde'), ('KY', 'Cayman Islands'), ('CF', 'Central African Republic'),
                      ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('KM', 'Comoros'),
                      ('CG', 'Congo'), ('CD', 'Congo (Democratic Republic of the)'), ('CK', 'Cook Islands'),
                      ('CR', 'Costa Rica'), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'),
                      ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'),
                      ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'),
                      ('EE', 'Estonia'), ('ET', 'Ethiopia'), ('FK', 'Falkland Islands (Malvinas)'), ('FO', 'Faroe Islands'),
                      ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'),
                      ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'),
                      ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'),
                      ('GT', 'Guatemala'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'),
                      ('VA', 'Holy See'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'),
                      ('IN', 'India'), ('ID', 'Indonesia'), ('CI', "Côte d'Ivoire"), ('IR', 'Iran (Islamic Republic of)'),
                      ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'),
                      ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KW', 'Kuwait'),
                      ('KG', 'Kyrgyzstan'), ('LA', "Lao People's Democratic Republic"), ('LV', 'Latvia'), ('LB', 'Lebanon'),
                      ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'),
                      ('LU', 'Luxembourg'), ('MO', 'Macao'), ('MK', 'Macedonia (the former Yugoslav Republic of)'),
                      ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'),
                      ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'),
                      ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia (Federated States of)'),
                      ('MD', 'Moldova (Republic of)'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('MS', 'Montserrat'),
                      ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'),
                      ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'),
                      ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk Island'),
                      ('KP', "Korea (Democratic People's Republic of)"), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'),
                      ('PW', 'Palau'), ('PS', 'Palestine, State of'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'),
                      ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('PL', 'Poland'),
                      ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RO', 'Romania'), ('RU', 'Russian Federation'),
                      ('RW', 'Rwanda'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('KN', 'Saint Kitts and Nevis'),
                      ('LC', 'Saint Lucia'), ('MF', 'Saint Martin (French part)'), ('PM', 'Saint Pierre and Miquelon'),
                      ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'),
                      ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'),
                      ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SK', 'Slovakia'), ('SI', 'Slovenia'),
                      ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('KR', 'Korea (Republic of)'),
                      ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SZ', 'Swaziland'),
                      ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syrian Arab Republic'), ('TJ', 'Tajikistan'),
                      ('TZ', 'Tanzania, United Republic of'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'),
                      ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Turkey'),
                      ('TM', 'Turkmenistan'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'),
                      ('GB', 'United Kingdom of Great Britain and Northern Ireland'), ('US', 'United States of America'),
                      ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela (Bolivarian Republic of)'),
                      ('VN', 'Viet Nam'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'))
DESTINATION_CHOICE = CITIZENSHIP_CHOICE

EVENT_TYPE_CHOICE = ((1,'Course'), (2, 'Consultation'), (3, 'Lecture'), (4, 'Show'), (5, 'Talk'), (6, 'Workshop'), (7, 'Others'))
EVENT_FREQ_CHOICE = ((1,'Once'), (2,'Multiple'),(3,'Fexible'))
EVENT_DURATION_CHOICE = ((1, 'Less than 2 hours'), (2, '2 to 4 hours'), (3, '4 to 8 hours'),(4, 'More than 8 hours'))

ORG_TYPE_CHOICE = ((1, 'Association'), (2, 'Center'), (3, 'Club'), (4, 'Community'), (5, 'Company'),
                   (6, 'Cooperative/Collective'), (7, 'Government/Town Council/Village'), (8, 'Institute'),
                   (9, 'Museum'), (10, 'NGO/Foundation'), (11, 'Park'), (12, 'Political Party'),
                   (13, 'School/Nursery/Kindergarten'), (14, 'Social Enterprise'), (15, 'Society'),
                   (16, 'Station & Network'), (17, 'Support Group'), (18, 'Union'), (19, 'University'), (20, 'Others'))


EXPERTISE_CHOICE = ['Accounting & Auditing', 'Admin & Clerical', 'Automotive', 'Banking', 'Biotech', 'Broadcast',
                  'Business Development', 'Construction', 'Consultant', 'Customer Service', 'Design', 'Distribution',
                  'Education', 'Engineering', 'Entry Level', 'Executive', 'Facilities', 'Finance', 'Franchise',
                  'General Business', 'General Labor', 'Government', 'Grocery', 'Health Care', 'Hospitality',
                  'Hotel', 'Human Resources', 'Information Technology', 'Installation', 'Insurance', 'Inventory',
                  'Journalism', 'Journalism', 'Legal', 'Legal Admin', 'Maint', 'Management', 'Manufacturing',
                  'Marketing', 'Media', 'New Grad', 'Newspaper', 'Nonprofit', 'Nurse', 'Other', 'Pharmaceutical',
                  'Planning', 'Procurement', 'Professional Services', 'Purchasing', 'QA', 'Quality Control',
                  'Real Estate', 'Repair', 'Research', 'Restaurant/Food Service', 'Retail', 'Sales', 'Science',
                  'Shipping', 'Skilled Labor', 'Social Services', 'Strategy', 'Supply Chain', 'Teaching',
                  'Telecommunications', 'Trades', 'Training', 'Transportation', 'Warehouse']


LANGUAGE_CHOICE = ['Abkhaz', 'Afar', 'African', 'Afrikaans', 'Akan', 'Albanian', 'Alemannic', 'Alsatian', 'Amerindian',
             'Amerindian dialects', 'Amharic', 'Angaur', 'Arabic', 'Aramaic', 'Armenian', 'Asian', 'Assamese',
             'Assyrian', 'Aymara', 'Azerbaijani', 'Azeri', 'Bahasa', 'Bahasa Indonesia', 'Balinese', 'Balochi',
             'Baluchi', 'Bambara', 'Bandjabi', 'Bangla', 'Bantu', 'Bapounou/Eschira', 'Barbuda', 'Bari', 'Basque',
             'Belorussian/White Russian', 'Bemba', 'Bengali', 'Berber', 'Bhojpuri', 'Bhotes', 'Bicol', 'Bislama',
             'Bojpoori', 'Bokmål Norwegian', 'Bosnian', 'Brahui', 'Brazilero', 'Breton', 'Bubi', 'Bulgarian', 'Burmese',
             'Burushaski', 'Cakchiquel', 'Cantonese', 'Carib', 'Carolinian', 'Castilian', 'Catalan', 'Catalán',
             'Cebuano', 'Chichewa', 'Chilomwe', 'Chinese/Mandarin', 'Chinyanja', 'Chisena', 'Chitonga', 'Chitumbuka',
             'Chiyao', 'Chukese', 'Circassian', 'Cisena', 'Corsican', 'Creole', 'Criolo', 'Criuolo', 'Croatian',
             'Cushitic', 'Czech', 'Dagomba', 'Danish', 'Dari', 'Dimli', 'Dinka', 'Dioula', 'Djerma', 'Dutch',
             'Dutch/Flemish', 'Dzongkha', 'Echuwabo', 'Elomwe', 'Emakhuwa', 'English', 'Estonian', 'Ewe', 'Ewé',
             'Fang', 'Faroese', 'Farsi', 'Fijian', 'Filipino', 'Finnish', 'Flemish', 'Fon', 'Foochow', 'French',
             'French patois', 'Frisian', 'Fula', 'Fulani', 'Fuzhou', 'Ga', 'Gaelic', 'Gagauz', 'Galician', 'Galole',
             'Gan', 'Ganda', 'Garifuna', 'Georgian', 'German', 'Greek', 'Greenlandic', 'Guaragigna', 'Guaraní', 'Gujarati',
             'Hainan', 'Haitian', 'Hakka', 'Hassaniya Arabic', 'Hausa', 'Hebrew', 'Herero', 'Hiligaynon', 'Hindi',
             'Hindi/Urdu', 'Hindko', 'Hindustani', 'Hiri Motu', 'Hokkien', 'Hokkien-Taiwanese', 'Hungarian',
             'I-Kiribati', 'Iban', 'Ibo', 'Icelandic', 'Ilocano', 'Ilonggo', 'Indian', 'Indonesia', 'Inuit',
             'Irish', 'IsiXhosa', 'IsiZulu', 'Italian', 'Jamaican', 'Japanese', 'Javanese', 'Jola', 'Kabardian',
             'Kabyé', 'Kadazan', 'Kalanga', 'Kannada', 'Kaonda', 'Kapingamarangi', 'Kashmiri', 'Kazak', 'Kekchi',
             'Kemak', 'Khmer', 'Kikongo', 'Kinyarwanda', 'Kiribati', 'Kirundi', 'Kiswahili', 'Korean', 'Kosrean',
             'Krio', 'Kunama', 'Kurdish', 'Kyrgyz', 'Lao', 'Latin', 'Latvian', 'Lingala', 'Lithuanian', 'Lozi', 'Luganda',
             'Lunda', 'Luri', 'Luvale', 'Luxermbourgish', 'Macedonian', 'Maithali', 'Malagasy', 'Malay', 'Malayalam',
             'Malayo-Polynesian', 'Maldivian Dhivehi', 'Malinké', 'Maltese', 'Mam', 'Mambae', 'Mandinka',
             'Maori', 'Marathi', 'Marshallese', 'Mayan', 'Melanesian', 'Melayu', 'Mende', 'Min', 'Mina', 'Minbei',
             'Minnan', 'Mirandese', 'Moldovan', 'Mon-Khmer', 'Mongolian', 'Monokutuba', 'Montenegrin',
             'Monégasque', 'Moroccan Arabic', 'Moshi-Dagomba', 'Mozambican', 'Myene', 'Nahua', 'Nahuatl', 'Nama',
             'Nauruan', 'Ndebele/Sindebele', 'Nepalese', 'Nepali', 'Niger-Congo', 'Nilo-Hamitic', 'Nilo-Saharan', 'Nilotic',
             'Nordic', 'Nubian', 'Nuer', 'Nui', 'Nukuoro', 'Nyanja', 'Nynorsk Norwegian', 'Nzebi', 'Oriya', 'Orominga',
             'Oshivambo', 'Palauan', 'Pampango', 'Pangasinense', 'Panjabi', 'Pashtu', 'Persian', 'Pohnpeian', 'Polish',
             'Portuguese', 'Portunol', 'Provençal', 'Pulaar', 'Punjabi', 'Quechua', 'Quiche', 'Quéchua', 'Roma', 'Romanian',
             'Romansch', 'Russian', 'Sami', 'Samoan', 'Sangho', 'Sanskrit', 'Sara', 'Scots Gaelic',
             'Sekgalagadi', 'Sepedi', 'Serbian', 'Serbo-Croatian', 'Seselwa Creole', 'Sesotho', 'Setswana', 'Shanghaiese',
             'Shikomoro', 'Shilluk', 'Shona', 'Siamese', 'Sindhi', 'Sinhala', 'Siraiki', 'Siswati', 'Slovak', 'Slovene',
             'Slovenian', 'Somali', 'Soninke', 'Sonsoralese', 'Spanish', 'Sudanic', 'Surinamese', 'Susu', 'Swahili',
             'Swahili/Arabic', 'Swedish', 'Ta Bedawie', 'Tagalog', 'Taiwanese', 'Tajik', 'Tamang', 'Tamil', 'Telugu',
             'Temne', 'Teochew', 'Tetum', 'Thai', 'Tharu', 'Tibetan', 'Tigre', 'Tigrigna', 'Tigrinya', 'Tobi', 'Tok Pisin',
             'Tonga', 'Tongan', 'Tosk', 'Tshiluba', 'Turkic', 'Turkish', 'Turkmen', 'Tuvaluan', 'Ukrainian', 'Ulithian',
             'Urdu', 'Uzbek', 'Vietnamese', 'Waray', 'Welsh', 'Woleaian', 'Wolof', 'Wu', 'Xhosa', 'Xiang', 'Xichangana',
             'Xinca', 'Xitsonga', 'Yapase', 'Yezidi', 'Yoruba', 'Yue', 'Zande', 'Zulu']

TOPIC_CHOICE = ()