# Generated by Django 2.2 on 2019-05-10 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileorganization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileorganization',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='profileorganization',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Association'), (2, 'Center'), (3, 'Club'), (4, 'Community'), (5, 'Company'), (6, 'Cooperative/Collective'), (7, 'Government/Town Council/Village'), (8, 'Institute'), (9, 'Museum'), (10, 'NGO/Foundation'), (11, 'Park'), (12, 'Political Party'), (13, 'School/Nursery/Kindergarten'), (14, 'Social Enterprise'), (15, 'Society'), (16, 'Station & Network'), (17, 'Support Group'), (18, 'Union'), (19, 'University'), (20, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='profileperson',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileperson',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.CreateModel(
            name='ProfileStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('completed_perc', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
