# Generated by Django 2.2 on 2019-05-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
    ]
